ALTER TABLE company_features DROP CONSTRAINT IF EXISTS ck_company_feature;
ALTER TABLE company_features ADD CONSTRAINT ck_company_feature CHECK (feature IN ('DASHBOARD','CLIENTS','PRODUCTS','PURCHASES','NEW_SALE','SALES','RECEIVABLES','ORDERS','ROUTES','REPORTS','CHARTS','SETTINGS','FIXED_EXPENSES','PROMOTIONS'));
