ALTER TABLE company_features DROP CONSTRAINT IF EXISTS ck_company_feature;
ALTER TABLE company_features ADD CONSTRAINT ck_company_feature CHECK (feature IN ('DASHBOARD','CLIENTS','PRODUCTS','PURCHASES','NEW_SALE','SALES','RECEIVABLES','ORDERS','ROUTES','REPORTS','CHARTS','SETTINGS','FIXED_EXPENSES','PROMOTIONS','COURIERS','SNACKS','NOTES','KITCHEN','SNACK_COSTS','SNACK_STATS','CASH'));

ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS kitchen_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS cost_total NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) NOT NULL DEFAULT 'PIX';
ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS cash_received NUMERIC(14,2);
ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS change_amount NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE vendas ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) NOT NULL DEFAULT 'PIX';
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS cash_received NUMERIC(14,2);
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS change_amount NUMERIC(14,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS snack_recipe_items (
  id UUID PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  snack_id UUID NOT NULL REFERENCES snacks(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
  quantity NUMERIC(14,3) NOT NULL DEFAULT 1,
  CONSTRAINT uk_snack_recipe_product UNIQUE (snack_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_snack_recipe_company_snack ON snack_recipe_items(company_id, snack_id);
