ALTER TABLE company_features DROP CONSTRAINT IF EXISTS ck_company_feature;
ALTER TABLE company_features ADD CONSTRAINT ck_company_feature CHECK (feature IN ('DASHBOARD','CLIENTS','PRODUCTS','PURCHASES','NEW_SALE','SALES','RECEIVABLES','ORDERS','ROUTES','REPORTS','CHARTS','SETTINGS','FIXED_EXPENSES','PROMOTIONS','COURIERS','SNACKS','NOTES','KITCHEN','SNACK_COSTS','SNACK_STATS','CASH','BEVERAGES'));
CREATE TABLE beverages (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE, name VARCHAR(160) NOT NULL, price NUMERIC(14,2) NOT NULL, cost NUMERIC(14,2) NOT NULL DEFAULT 0);
CREATE INDEX idx_beverages_company_name ON beverages(company_id,name);
