
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS modo_taxa_cliente VARCHAR(30) NOT NULL DEFAULT 'PERCENT';
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS taxa_entrega NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE snack_orders ADD COLUMN IF NOT EXISTS order_info TEXT;
